{"created": 1760590211.7194037, "duration": 0.6274938583374023, "exitcode": 2, "root": "C:\\Users\\sudha\\OneDrive\\Desktop\\deploy", "environment": {}, "summary": {"total": 0, "collected": 0}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "fastapi_todo_app/tests", "type": "Dir"}, {"nodeid": "flask_hello_app/tests", "type": "Dir"}, {"nodeid": "flask_users_app/tests", "type": "Dir"}]}, {"nodeid": "fastapi_todo_app/tests/test_main.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module 'C:\\Users\\sudha\\OneDrive\\Desktop\\deploy\\fastapi_todo_app\\tests\\test_main.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\nC:\\Python314\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nfastapi_todo_app\\tests\\test_main.py:5: in <module>\n    from main import app  # Local\n    ^^^^^^^^^^^^^^^^^^^^\nE   ModuleNotFoundError: No module named 'main'"}, {"nodeid": "fastapi_todo_app/tests", "outcome": "passed", "result": [{"nodeid": "fastapi_todo_app/tests/test_main.py", "type": "Module"}]}, {"nodeid": "flask_hello_app/tests/test_app.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module 'C:\\Users\\sudha\\OneDrive\\Desktop\\deploy\\flask_hello_app\\tests\\test_app.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\nC:\\Python314\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nflask_hello_app\\tests\\test_app.py:3: in <module>\n    from app import app  # Local\n    ^^^^^^^^^^^^^^^^^^^\nE   ModuleNotFoundError: No module named 'app'"}, {"nodeid": "flask_hello_app/tests", "outcome": "passed", "result": [{"nodeid": "flask_hello_app/tests/test_app.py", "type": "Module"}]}, {"nodeid": "flask_users_app/tests/test_app.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module 'C:\\Users\\sudha\\OneDrive\\Desktop\\deploy\\flask_users_app\\tests\\test_app.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\nC:\\Python314\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nflask_users_app\\tests\\test_app.py:3: in <module>\n    from app import app  # Local\n    ^^^^^^^^^^^^^^^^^^^\nE   ModuleNotFoundError: No module named 'app'"}, {"nodeid": "flask_users_app/tests", "outcome": "passed", "result": [{"nodeid": "flask_users_app/tests/test_app.py", "type": "Module"}]}], "tests": [], "warnings": [{"message": "Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.", "category": "UserWarning", "when": "collect", "filename": "C:\\Users\\sudha\\OneDrive\\Desktop\\deploy\\venv311\\Lib\\site-packages\\fastapi\\_compat\\v1.py", "lineno": 72}]}