{
  "errors": [
    {
      "filename": "fastapi_todo_app\\main.py",
      "reason": "exception while scanning file"
    },
    {
      "filename": "fastapi_todo_app\\tests\\test_main.py",
      "reason": "exception while scanning file"
    },
    {
      "filename": "flask_hello_app\\app.py",
      "reason": "exception while scanning file"
    },
    {
      "filename": "flask_hello_app\\tests\\test_app.py",
      "reason": "exception while scanning file"
    },
    {
      "filename": "flask_users_app\\app.py",
      "reason": "exception while scanning file"
    },
    {
      "filename": "flask_users_app\\tests\\test_app.py",
      "reason": "exception while scanning file"
    }
  ],
  "generated_at": "2025-10-16T03:34:20Z",
  "metrics": {
    "_totals": {
      "CONFIDENCE.HIGH": 0,
      "CONFIDENCE.LOW": 0,
      "CONFIDENCE.MEDIUM": 0,
      "CONFIDENCE.UNDEFINED": 0,
      "SEVERITY.HIGH": 0,
      "SEVERITY.LOW": 0,
      "SEVERITY.MEDIUM": 0,
      "SEVERITY.UNDEFINED": 0,
      "loc": 87,
      "nosec": 0,
      "skipped_tests": 0
    },
    "fastapi_todo_app\\main.py": {
      "loc": 12,
      "nosec": 0,
      "skipped_tests": 0
    },
    "fastapi_todo_app\\tests\\test_main.py": {
      "loc": 19,
      "nosec": 0,
      "skipped_tests": 0
    },
    "flask_hello_app\\app.py": {
      "loc": 10,
      "nosec": 0,
      "skipped_tests": 0
    },
    "flask_hello_app\\tests\\test_app.py": {
      "loc": 15,
      "nosec": 0,
      "skipped_tests": 0
    },
    "flask_users_app\\app.py": {
      "loc": 14,
      "nosec": 0,
      "skipped_tests": 0
    },
    "flask_users_app\\tests\\test_app.py": {
      "loc": 17,
      "nosec": 0,
      "skipped_tests": 0
    }
  },
  "results": []
}